import { readFile } from "node:fs/promises";
const readme=await readFile(new URL("../README.md",import.meta.url),"utf8");
const image=await readFile(new URL("../docs/assets/repopack-hero.png",import.meta.url));
const sig=Buffer.from([0x89,0x50,0x4e,0x47,0x0d,0x0a,0x1a,0x0a]);
if(!image.subarray(0,8).equals(sig)) throw new Error("hero is not PNG");
const ihdr=image.indexOf(Buffer.from("IHDR")); const width=image.readUInt32BE(ihdr+4),height=image.readUInt32BE(ihdr+8);
if(width!==1536||height!==860) throw new Error(`hero must be 1536x860, got ${width}x${height}`);
if(image.length<10000) throw new Error(`hero too small: ${image.length}`);
if(!readme.includes("docs/assets/repopack-hero.png")) throw new Error("README does not reference PNG hero");
if(/<img[^>]+src=["'][^"']+\.svg/i.test(readme)) throw new Error("SVG hero forbidden");
process.stdout.write(`Hero verified: ${width}x${height}, ${image.length} bytes.\n`);
